# Generated by Django 4.1.5 on 2023-12-16 08:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_noteuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
