# Generated by Django 4.1.5 on 2023-12-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_noteuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteuser',
            name='id',
            field=models.UUIDField(default='de7822efe3f147078788399b30e9b560', editable=False, primary_key=True, serialize=False),
        ),
    ]
