# Generated by Django 4.1.5 on 2023-12-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_noteuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteuser',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
